version: '3'
services:
  container-a:
    container_name: ${COMPOSE_PREFIX}container-a
    build: ./.docker/contaniner-a
    volumes:
      # Data and Logs
      - ./data/container-a/:/etc/data/
      - ./logs/container-a/:/etc/logs/
      # Dev
      - ./.docker/container-a/os/file.conf:/etc/path-inside-container.conf
    networks:
      - shared-network
      - private-network-A
    ports:
      #- "80:80"   #127.0.0.1
      #- "8080:80" #127.0.0.1:8080
      #- "8000:80" #127.0.0.1:8000
      - "local-port:container-port"
  container-b:
    container_name: ${COMPOSE_PREFIX}container-b
    build: ./.docker/contaniner-b
    volumes:
      # Data and Logs
      - ./data/container-b/:/etc/data/
      - ./logs/container-b/:/etc/logs/
      # Dev
      - ./.docker/container-a/os/file.conf:/etc/path-inside-container.conf
      - ./.docker/container-a/server/file.conf:/etc/path-inside-container.conf
      - ./.docker/container-a/language/file.conf:/etc/path-inside-container.conf
      - ./.docker/container-a/framework/file.conf:/etc/path-inside-container.conf
      - ./.docker/container-a/app/file.conf:/etc/path-inside-container.conf
    networks:
      - shared-network
      - private-network-B
    ports:
      #- "80:80"   #127.0.0.1
      #- "8080:80" #127.0.0.1:8080
      #- "8000:80" #127.0.0.1:8000
      - "local-port:container-port"
  networks:
    shared-network:
    private-network-A:
    private-network-B: